In [1]:
import numpy as np

In [2]:
u = np.array([[1,2],[3,4]])
u

array([[1, 2],
       [3, 4]])

In [4]:
u[1][1]

4

In [5]:
u[1,1]

4

In [7]:
ex1 = np.zeros((2,2))

In [8]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [11]:
ex2 = np.eye(2,2)
ex2

array([[1., 0.],
       [0., 1.]])

In [7]:
ex3= np.random.random((4,4))

In [15]:
ex3

array([[0.31909879, 0.97239206, 0.85317453, 0.2346381 ],
       [0.77729669, 0.99870237, 0.57444154, 0.13922882],
       [0.51682167, 0.95273053, 0.67319579, 0.78487782],
       [0.3128168 , 0.5552359 , 0.17942683, 0.2290293 ]])

In [8]:
#refrence 

a_slice = ex3[:2 , 1:3] # a_slice does not consist of last numbers

In [9]:
a_slice

array([[0.32976752, 0.06379004],
       [0.16049483, 0.03207399]])

In [10]:
a_slice[1,1] = 1

In [11]:
ex3 # changed 

array([[0.08683423, 0.32976752, 0.06379004, 0.20619959],
       [0.80437424, 0.16049483, 1.        , 0.51139535],
       [0.02492031, 0.69564252, 0.82046378, 0.43602603],
       [0.97607836, 0.42635834, 0.90912228, 0.71497135]])

In [24]:
# make a copy

another_slice = np.array(ex3[:2 , 1:3])

In [25]:
another_slice[1,1] =2

In [27]:
ex3 # unchanged

array([[0.31909879, 0.97239206, 0.85317453, 0.2346381 ],
       [0.77729669, 0.99870237, 1.        , 0.13922882],
       [0.51682167, 0.95273053, 0.67319579, 0.78487782],
       [0.3128168 , 0.5552359 , 0.17942683, 0.2290293 ]])

In [28]:
row_rankOne = ex3[1,:]
row_rankOne 

array([0.77729669, 0.99870237, 1.        , 0.13922882])

In [30]:
row_rankOne.shape # rank 1 

(4,)

In [32]:
row_rankTwo = ex3[1:2,:]
row_rankTwo # two brackets

array([[0.77729669, 0.99870237, 1.        , 0.13922882]])

In [33]:
row_rankTwo.shape # rank 2 

(1, 4)

In [4]:
col_indexes = np.array([0,1,2,0])
row_indexes = np.arange(4)

In [5]:
for row , col in zip(row_indexes,col_indexes): print(row ," , ", col)

0  ,  0
1  ,  1
2  ,  2
3  ,  0


In [13]:
ex3

array([[0.08683423, 0.32976752, 0.06379004, 0.20619959],
       [0.80437424, 0.16049483, 1.        , 0.51139535],
       [0.02492031, 0.69564252, 0.82046378, 0.43602603],
       [0.97607836, 0.42635834, 0.90912228, 0.71497135]])

In [12]:
ex3[row_indexes , col_indexes]

array([0.08683423, 0.16049483, 0.82046378, 0.97607836])

In [14]:
ex3[row_indexes , col_indexes] += 1000

In [15]:
ex3

array([[1.00008683e+03, 3.29767517e-01, 6.37900354e-02, 2.06199590e-01],
       [8.04374236e-01, 1.00016049e+03, 1.00000000e+00, 5.11395346e-01],
       [2.49203077e-02, 6.95642515e-01, 1.00082046e+03, 4.36026034e-01],
       [1.00097608e+03, 4.26358343e-01, 9.09122276e-01, 7.14971351e-01]])

# Boolean Indexing

In [17]:
an_array = np.array([[11,12], [21,22],[31,32]])
an_array

array([[11, 12],
       [21, 22],
       [31, 32]])

In [19]:
filter = an_array > 15
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [20]:
an_array[filter]

array([21, 22, 31, 32])

In [23]:
an_array[(an_array > 20) & (an_array < 30)]

array([21, 22])

In [24]:
u = np.array([[1,2],[3,4]])
u.dtype

dtype('int32')

In [30]:
v = np.array([[1,2],[3,4]],dtype = np.int64)
v.dtype

dtype('int64')

In [31]:
v

array([[1, 2],
       [3, 4]], dtype=int64)

In [32]:
v[1,1] += 0.4
v

array([[1, 2],
       [3, 4]], dtype=int64)

In [33]:
v = np.array([[1,2],[3,4]],dtype = np.float)
v.dtype

dtype('float64')

In [34]:
v

array([[1., 2.],
       [3., 4.]])

In [35]:
v[1,1] += 0.4
v

array([[1. , 2. ],
       [3. , 4.4]])

In [36]:
new = v + u # up casting to float

In [37]:
new

array([[2. , 4. ],
       [6. , 8.4]])

In [38]:
np.sqrt(u)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [39]:
arr = 10 * np.random.randn(2,5)
arr

array([[  8.94725832,   2.51927021,  -7.41970215, -10.29846675,
          0.60622999],
       [ 19.04502397,   2.65929951,  -8.43852087,  -6.96565347,
          3.21966601]])

In [41]:
arr.mean()

0.38744047806482884

In [42]:
# for each row

arr.mean(axis = 1)

array([-1.12908208,  1.90396303])

In [43]:
# for each column

arr.mean(axis = 0)

array([13.99614115,  2.58928486, -7.92911151, -8.63206011,  1.912948  ])

In [44]:
arr.sum()

3.8744047806482884

In [46]:
arr

array([[  8.94725832,   2.51927021,  -7.41970215, -10.29846675,
          0.60622999],
       [ 19.04502397,   2.65929951,  -8.43852087,  -6.96565347,
          3.21966601]])

In [45]:
np.median(arr,axis=1)

array([0.60622999, 2.65929951])

In [48]:
unsorted = np.random.randn(10)
unsorted

array([-0.44499102,  1.16901142, -1.01616662, -0.5490947 , -0.47907231,
       -0.04982647,  1.17355862, -0.48763098, -0.0524215 ,  1.23508145])

In [51]:
# a sorted copy
sorted = np.array(unsorted)
sorted.sort()
sorted

array([-1.01616662, -0.5490947 , -0.48763098, -0.47907231, -0.44499102,
       -0.0524215 , -0.04982647,  1.16901142,  1.17355862,  1.23508145])

In [52]:
unsorted

array([-0.44499102,  1.16901142, -1.01616662, -0.5490947 , -0.47907231,
       -0.04982647,  1.17355862, -0.48763098, -0.0524215 ,  1.23508145])

In [54]:
unsorted.sort()
unsorted

array([-1.01616662, -0.5490947 , -0.48763098, -0.47907231, -0.44499102,
       -0.0524215 , -0.04982647,  1.16901142,  1.17355862,  1.23508145])

In [55]:
array = np.array([1,2,1,3,4,1,2])

In [56]:
np.unique(array)

array([1, 2, 3, 4])

In [59]:
a1 = np.array([1,2,3])
a2 = np.array([1,5,2])

In [60]:
# common elements
np.intersect1d(a1,a2)

array([1, 2])

In [61]:
np.union1d(a1,a2)

array([1, 2, 3, 5])

In [62]:
np.setdiff1d(a1,a2) # in a1 but not in a2

array([3])

In [63]:
np.in1d(a1,a2) # which elements of a1 are also in a2

array([ True,  True, False])

In [67]:
a1 = np.array([[1,2,3,4]])
(a1).shape , (a1.T).shape

((1, 4), (4, 1))